### PR TITLE
feature: customizable URLSessionConfiguration

### PR DESCRIPTION
**Pull request by jens-robert**
customizable URLSessionConfiguration

### CODE REVIEW

**Comment by nsagnett** [comment]
Hello Jens ! 

We created a new branch (https://github.com/at-internet/atinternet-apple-sdk/tree/feature/proxying), to customize session for proxy usage and you can try with this kind of syntax:
```
tracker.setProxyType(ProxyTypeKey.http)
tracker.setProxyAddress("127.0.0.1:8000")
```

**Comment by jens-robert** [comment]
Hello,

thanks for the branch 'proxying'. Your way looks much more better. I will close my pull request.

Thanks - Jens

**Comment by nsagnett** [comment]
Hello ! 

Have you tried the "proxying" branch ? Does it match with your constraint ?

Regards,

**Comment by jrkorth** [comment]
i didn't test it yet. We will start the implementation and testing on Monday - 16.11.2020.

**Comment by jrkorth** [comment]
Hello,

your "proxying" branch works fine for us!
When will it be merged in the master?

Thanks - Jens

**Comment by nsagnett** [comment]
Hello,

It's available now from master branch

Regards,

**Comment by jrkorth** [comment]
Hello,

thanks for the faster merge.
Now we switch back to the master (2.21).

But something goes wrong in the current Storage class (line 473).
The app terminates every time with:
"_Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'The specified URI is not a valid Core Data URI: https://logs••••.xiti.com/hit.xiti?s=…_"

Is the master broken?

Thanks - Jens

**Comment by nsagnett** [comment]
It's an unexpected case , can you try with https://github.com/at-internet/atinternet-apple-sdk/tree/fix/core_data_uri branch ?

**Comment by jrkorth** [comment]
Yes!

**Comment by nsagnett** [comment]
If it's ok for you, I will push fix on master asap

**Comment by jrkorth** [comment]
Hello,

i try:
pod 'ATInternet-Apple-SDK/Tracker', :git => 'https://github.com/at-internet/atinternet-apple-sdk.git', :branch => 'fix/core_data_uri'

and it works!

Thanks

**Comment by nsagnett** [comment]
Many thanks ! It merged on master now 

Sorry for the inconvenience

Regards,

**Comment by jrkorth** [comment]
You're welcome!

Thanks for all.

**Pull request closed without merging**
